### PR TITLE
Gela8178/upgrade

### PR DESCRIPTION
**Pull request by Gela**
Upgrading Assimp to 5.0. Needed for update 7

3rd party vtest: http://runtime-test.esri.com:8080/view/vTest/job/vtest-3rdparty_libraries-interface/451/downstreambuildview/

android x64: http://runtime-test.esri.com:8080/job/vtest-3rdparty_libraries-android/426/
android x86: http://runtime-test.esri.com:8080/job/vtest-3rdparty_libraries-interface/447/downstreambuildview/

Win x86: http://runtime-test.esri.com:8080/view/vTest/job/vtest-3rdparty_libraries-interface/448/

iOS Sim64: http://runtime-test.esri.com:8080/view/vTest/job/vtest-3rdparty_libraries-interface/449/

winUWP x64: http://runtime-test.esri.com:8080/view/vTest/job/vtest-3rdparty_libraries-interface/450/
WinUWP arm: http://runtime-test.esri.com:8080/job/vtest-3rdparty_libraries-winuwp/371/
WinUWP arm64: http://runtime-test.esri.com:8080/job/vtest-3rdparty_libraries-winuwp/372/

vTest link coming soon (waiting on 3rd party to build)

### CODE REVIEW

**Comment by jsigrist** [comment]
Should this be merged into master? The way the branches are set up right now is to have `Esri/assimp/master` track `assimp/assimp/master`. The Esri/assimp/runtimecore branch is whatever tag of upstream master we want (probably their 5.0 release tag), then whatever commits we need on top of that

**Comment by jsigrist** [comment]
An easier way to do this might be to create a branch `A` that is just a copy of Assimp's `release/100.5.0` branch, then a branch `B` with the RTC changes to 100.5. We could review a PR of `B` into `A` to get just the RTC changes. Then once that's merged just do a hard reset of `/runtimecore` to branch `A`. That would make the history of `runtimecore` nice and clean, and easy to get just the RTC commits when we need to move to the next version.

**Comment by chri7325** [comment]
@jsigrist that's a strategy that I use when moving a branch up cannot be done but it ends up being somewhat destructive to the runtimecore branch and doesn't provide the full history so I save it when it isn't possible to merge in tags. For example, if a 3rdparty does a branch to release strategy. Doing it this way gives us the full history of core's usage. I like and hate both as they each have their pros and cons.

**Comment by jsigrist** [comment]
Oh that makes sense, I wasn't thinking about needing previous tags of runtimecore.

**Comment by jsigrist** [comment]
So are the relevant changes just the ones since

`Merge tag 'v5.0.0' into gela8178/upgrade (9c86e75)`

**Comment by chri7325** [comment]
Well, luckily the tags would still be viable even if the history of the branch would be rewritten so we'd still be able to see older builds and use them. However, we would just lose the full history of ALL changes that were made and why they were made in this branch and every upgrade would more or less require replaying these again.  The hope is that we can keep changes minimal and hopefully without conflicts so all updates would be easy. For example, you can compare this branch with master and get a full changeset of everything that we ever needed for this https://github.com/Esri/assimp/compare/master...Esri:gela8178/upgrade.

**Comment by jsigrist** [comment]
Oh, that link is super helpful. Got it.

**Pull request merged**
